analyzer:
  errors:
    constant_identifier_names: ignore
    curly_braces_in_flow_control_structures: ignore
    non_constant_identifier_names: ignore
    prefer_interpolation_to_compose_strings: ignore
    sort_child_properties_last: ignore
    unnecessary_this: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
